version: '3.1'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql